import { getRandomDate } from "./lib/utils";

// Resource Cards
const gradeCards = [
  { id: "grade1", grade: "Grade 1" },
  { id: "grade2", grade: "Grade 2" },
  { id: "grade3", grade: "Grade 3" },
  { id: "Grade4", grade: "Grade 4" },
  { id: "Grade5", grade: "Grade 5" },
  { id: "Grade6", grade: "Grade 6" },
  { id: "Grade7", grade: "Grade 7" },
  { id: "Grade8", grade: "Grade 8" },
  { id: "Grade9", grade: "Grade 9" },
  { id: "Grade10", grade: "Grade 10" },
  { id: "Grade11", grade: "Grade 11" },
  { id: "Grade12", grade: "Grade 12" },
];
const phaseCards = [
  {
    id: "Foundation",
    name: "Foundation Phase",
  },
  {
    id: "Intermediate",
    name: "Intermediate Phase",
  },
  {
    id: "Senior",
    name: "Senior Phase",
  },
  {
    id: "FET",
    name: "FET Phase",
  },
];
const categoryCards = [
  {
    id: "Algebra1",
    name: "Algebra",
  },
  {
    id: "Geometry2",
    name: "Geometry",
  },
  {
    id: "Trigonometry3",
    name: "Trigonometry",
  },
  {
    id: "Calculus4",
    name: "Calculus",
  },
  {
    id: "Statistics5",
    name: "Statistics",
  },
  {
    id: "NumberTheory6",
    name: "Number Theory",
  },
  {
    id: "Finance7",
    name: "Finance",
  },
  {
    id: "LinearEquations8",
    name: "Linear Equations",
  },
  {
    id: "ShapesAndTheorems9",
    name: "Shapes and Theorems",
  },
  {
    id: "TrigonometricRatios10",
    name: "Trigonometric Ratios",
  },
  {
    id: "Differentiation11",
    name: "Differentiation",
  },
  {
    id: "DataAnalysis12",
    name: "Data Analysis",
  },
  {
    id: "NumberPatterns13",
    name: "Number Patterns",
  },
  {
    id: "InterestCalculations14",
    name: "Interest Calculations",
  },
  {
    id: "Probability15",
    name: "Probability",
  },
  {
    id: "ComplexNumbers16",
    name: "Complex Numbers",
  },
  {
    id: "AlgebraIntermediate",
    name: "Algebra Intermediate",
  },
  {
    id: "GeometryIntermediate",
    name: "Geometry Intermediate",
  },
  {
    id: "TrigonometryIntermediate",
    name: "Trigonometry Intermediate",
  },
  {
    id: "CalculusIntermediate",
    name: "Calculus Intermediate",
  },
  {
    id: "StatisticsIntermediate",
    name: "Statistics Intermediate",
  },
  {
    id: "NumberTheoryIntermediate",
    name: "Number Theory Intermediate",
  },
  {
    id: "FinanceIntermediate",
    name: "Finance Intermediate",
  },
  {
    id: "LinearEquationsIntermediate",
    name: "Linear Equations Intermediate",
  },
  {
    id: "ShapesAndTheoremsIntermediate",
    name: "Shapes and Theorems Intermediate",
  },
  {
    id: "TrigonometricRatiosIntermediate",
    name: "Trigonometric Ratios Intermediate",
  },
  {
    id: "DifferentiationIntermediate",
    name: "Differentiation Intermediate",
  },
  {
    id: "DataAnalysisIntermediate",
    name: "Data Analysis Intermediate",
  },
  {
    id: "NumberPatternsIntermediate",
    name: "Number Patterns Intermediate",
  },
  {
    id: "InterestCalculationsIntermediate",
    name: "Interest Calculations Intermediate",
  },
  {
    id: "ProbabilityIntermediate",
    name: "Probability Intermediate",
  },
  {
    id: "ComplexNumbersIntermediate",
    name: "Complex Numbers Intermediate",
  },
];

const resourceCards = [
  {
    id: "1",
    title: "Algebra Basics",
    category: "Algebra",
    categoryId: "algebra1",
    description: "Introduction to algebraic concepts and operations.",
    grade: "Grade 8",
    gradeId: "grade8",
    phase: "Senior Phase",
    phaseId: "Senior",
    date: getRandomDate(),
    wakeletcode: `<iframe class="wakeletEmbed" width="100%" height="760px" src="https://embed.wakelet.com/wakes/HcLuyR2ESyD_gvY3_w7_L/list?border=1" style="border: none" allow="autoplay"></iframe><!-- Please only call https://embed-assets.wakelet.com/wakelet-embed.js once per page --><script src="https://embed-assets.wakelet.com/wakelet-embed.js" charset="UTF-8"></script>`,
  },
  {
    id: "2",
    title: "Geometry Fundamentals",
    category: "Geometry",
    categoryId: "geometry2",
    description:
      "Basic principles of geometry including shapes, angles, and theorems.",
    grade: "Grade 9",
    gradeId: "grade9",
    phase: "Senior Phase",
    phaseId: "Senior",
    date: getRandomDate(),
    wakeletcode: `<iframe class="wakeletEmbed" width="100%" height="760px" src="https://embed.wakelet.com/wakes/QKpGkQ47Q0i4MuiuM_F3R/list?border=1" style="border: none" allow="autoplay"></iframe><!-- Please only call https://embed-assets.wakelet.com/wakelet-embed.js once per page --><script src="https://embed-assets.wakelet.com/wakelet-embed.js" charset="UTF-8"></script>`,
  },
  {
    id: "3",
    title: "Trigonometry Essentials",
    category: "Trigonometry",
    categoryId: "trigonometry3",
    description: "Understanding trigonometric ratios and solving problems.",
    grade: "Grade 10",
    gradeId: "grade10",
    phase: "FET Phase",
    phaseId: "FET",
    date: getRandomDate(),
    wakeletcode: `<iframe class="wakeletEmbed" width="100%" height="760px" src="https://embed.wakelet.com/wakes/n6pMIqhxelAvXdulvTm8Y/list?border=1" style="border: none" allow="autoplay"></iframe><!-- Please only call https://embed-assets.wakelet.com/wakelet-embed.js once per page --><script src="https://embed-assets.wakelet.com/wakelet-embed.js" charset="UTF-8"></script>`,
  },
  {
    id: "4",
    title: "Calculus Introduction",
    category: "Calculus",
    categoryId: "calculus4",
    description:
      "Fundamentals of calculus including limits, derivatives, and integrals.",
    grade: "Grade 12",
    gradeId: "grade12",
    phase: "FET Phase",
    phaseId: "FET",
    date: getRandomDate(),
    wakeletcode: `<iframe class="wakeletEmbed" width="100%" height="760px" src="https://embed.wakelet.com/wakes/Rn7m1LseYdQIi9xnza_yL/list?border=1" style="border: none" allow="autoplay"></iframe><!-- Please only call https://embed-assets.wakelet.com/wakelet-embed.js once per page --><script src="https://embed-assets.wakelet.com/wakelet-embed.js" charset="UTF-8"></script>`,
  },
  {
    id: "5",
    title: "Statistics and Probability",
    category: "Statistics",
    categoryId: "statistics5",
    description: "Basic concepts of statistics and probability.",
    grade: "Grade 11",
    gradeId: "grade11",
    phase: "FET Phase",
    phaseId: "FET",
    date: getRandomDate(),
    wakeletcode: `<iframe class="wakeletEmbed" width="100%" height="760px" src="https://embed.wakelet.com/wakes/XWONoo47s-w5DlsksZ-uB/list?border=1" style="border: none" allow="autoplay"></iframe><!-- Please only call https://embed-assets.wakelet.com/wakelet-embed.js once per page --><script src="https://embed-assets.wakelet.com/wakelet-embed.js" charset="UTF-8"></script>`,
  },
  {
    id: "6",
    title: "Number Patterns",
    category: "Number Theory",
    categoryId: "numbertheory6",
    description: "Exploring number patterns and sequences.",
    grade: "Grade 7",
    gradeId: "grade7",
    phase: "Senior Phase",
    phaseId: "Senior",
    date: getRandomDate(),
    wakeletcode: `<iframe class="wakeletEmbed" width="100%" height="760px" src="https://embed.wakelet.com/wakes/ktKE5iCek2UrC3gKooMFp/list?border=1" style="border: none" allow="autoplay"></iframe><!-- Please only call https://embed-assets.wakelet.com/wakelet-embed.js once per page --><script src="https://embed-assets.wakelet.com/wakelet-embed.js" charset="UTF-8"></script>`,
  },
  {
    id: "7",
    title: "Financial Mathematics",
    category: "Finance",
    categoryId: "finance7",
    description:
      "Introduction to financial mathematics including interest calculations.",
    grade: "Grade 10",
    gradeId: "grade10",
    phase: "FET Phase",
    phaseId: "FET",
    date: getRandomDate(),
  },
  {
    id: "8",
    title: "Linear Equations",
    category: "Linear Equations",
    categoryId: "linearequations8",
    description:
      "Solving linear equations and understanding their applications.",
    grade: "Grade 8",
    gradeId: "grade8",
    phase: "Senior Phase",
    phaseId: "Senior",
    date: getRandomDate(),
  },
  {
    id: "9",
    title: "Shapes and Theorems",
    category: "Shapes and Theorems",
    categoryId: "shapesandtheorems9",
    description: "Exploring different shapes and their theorems.",
    grade: "Grade 9",
    gradeId: "grade9",
    phase: "Senior Phase",
    phaseId: "Senior",
    date: getRandomDate(),
  },
  {
    id: "10",
    title: "Trigonometric Ratios",
    category: "Trigonometric Ratios",
    categoryId: "trigonometricratios10",
    description: "Understanding and applying trigonometric ratios.",
    grade: "Grade 10",
    gradeId: "grade10",
    phase: "FET Phase",
    phaseId: "FET",
    date: getRandomDate(),
  },
  {
    id: "11",
    title: "Differentiation Basics",
    category: "Differentiation",
    categoryId: "differentiation11",
    description: "Introduction to differentiation and its applications.",
    grade: "Grade 12",
    gradeId: "grade12",
    phase: "FET Phase",
    phaseId: "FET",
    date: getRandomDate(),
  },
  {
    id: "12",
    title: "Data Analysis",
    category: "Data Analysis",
    categoryId: "dataanalysis12",
    description: "Basics of data analysis and interpretation.",
    grade: "Grade 11",
    gradeId: "grade11",
    phase: "FET Phase",
    phaseId: "FET",
    date: getRandomDate(),
  },
  {
    id: "13",
    title: "Number Patterns",
    category: "Number Patterns",
    categoryId: "numberpatterns13",
    description: "Exploring various number patterns and sequences.",
    grade: "Grade 7",
    gradeId: "grade7",
    phase: "Senior Phase",
    phaseId: "Senior",
    date: getRandomDate(),
  },
  {
    id: "14",
    title: "Interest Calculations",
    category: "Interest Calculations",
    categoryId: "interestcalculations14",
    description: "Understanding and calculating different types of interest.",
    grade: "Grade 10",
    gradeId: "grade10",
    phase: "FET Phase",
    phaseId: "FET",
    date: getRandomDate(),
  },
  {
    id: "15",
    title: "Probability Basics",
    category: "Probability",
    categoryId: "probability15",
    description: "Introduction to probability and its applications.",
    grade: "Grade 11",
    gradeId: "grade11",
    phase: "FET Phase",
    phaseId: "FET",
    date: getRandomDate(),
  },
  {
    id: "16",
    title: "Complex Numbers",
    category: "Complex Numbers",
    categoryId: "complexnumbers16",
    description: "Understanding and working with complex numbers.",
    grade: "Grade 12",
    gradeId: "grade12",
    phase: "FET Phase",
    phaseId: "FET",
    date: getRandomDate(),
  },
  {
    id: "17",
    title: "Algebra Advanced",
    category: "Algebra",
    categoryId: "algebra1",
    description: "Advanced algebraic concepts and operations.",
    grade: "Grade 9",
    gradeId: "grade9",
    phase: "Senior Phase",
    phaseId: "Senior",
    date: getRandomDate(),
  },
  {
    id: "18",
    title: "Geometry Advanced",
    category: "Geometry",
    categoryId: "geometry2",
    description:
      "Advanced principles of geometry including proofs and constructions.",
    grade: "Grade 10",
    gradeId: "grade10",
    phase: "FET Phase",
    phaseId: "FET",
    date: getRandomDate(),
  },
  {
    id: "19",
    title: "Trigonometry Advanced",
    category: "Trigonometry",
    categoryId: "trigonometry3",
    description: "Advanced trigonometric concepts and problem-solving.",
    grade: "Grade 11",
    gradeId: "grade11",
    phase: "FET Phase",
    phaseId: "FET",
    date: getRandomDate(),
  },
  {
    id: "20",
    title: "Calculus Advanced",
    category: "Calculus",
    categoryId: "calculus4",
    description: "Advanced calculus topics including integration techniques.",
    grade: "Grade 12",
    gradeId: "grade12",
    phase: "FET Phase",
    phaseId: "FET",
    date: getRandomDate(),
  },
  {
    id: "21",
    title: "Statistics Advanced",
    category: "Statistics",
    categoryId: "statistics5",
    description: "Advanced statistical methods and applications.",
    grade: "Grade 11",
    gradeId: "grade11",
    phase: "FET Phase",
    phaseId: "FET",
    date: getRandomDate(),
  },
  {
    id: "22",
    title: "Number Theory Advanced",
    category: "Number Theory",
    categoryId: "numbertheory6",
    description: "Advanced number theory concepts and applications.",
    grade: "Grade 12",
    gradeId: "grade12",
    phase: "FET Phase",
    phaseId: "FET",
    date: getRandomDate(),
  },
  {
    id: "23",
    title: "Finance Advanced",
    category: "Finance",
    categoryId: "finance7",
    description:
      "Advanced financial mathematics including investment analysis.",
    grade: "Grade 11",
    gradeId: "grade11",
    phase: "FET Phase",
    phaseId: "FET",
    date: getRandomDate(),
  },
  {
    id: "24",
    title: "Linear Equations Advanced",
    category: "Linear Equations",
    categoryId: "linearequations8",
    description: "Advanced techniques for solving linear equations.",
    grade: "Grade 10",
    gradeId: "grade10",
    phase: "FET Phase",
    phaseId: "FET",
    date: getRandomDate(),
  },
  {
    id: "25",
    title: "Shapes and Theorems Advanced",
    category: "Shapes and Theorems",
    categoryId: "shapesandtheorems9",
    description: "Advanced exploration of shapes and their theorems.",
    grade: "Grade 11",
    gradeId: "grade11",
    phase: "FET Phase",
    phaseId: "FET",
    date: getRandomDate(),
  },
  {
    id: "26",
    title: "Trigonometric Ratios Advanced",
    category: "Trigonometric Ratios",
    categoryId: "trigonometricratios10",
    description:
      "Advanced understanding and application of trigonometric ratios.",
    grade: "Grade 12",
    gradeId: "grade12",
    phase: "FET Phase",
    phaseId: "FET",
    date: getRandomDate(),
  },
  {
    id: "27",
    title: "Differentiation Advanced",
    category: "Differentiation",
    categoryId: "differentiation11",
    description: "Advanced differentiation techniques and applications.",
    grade: "Grade 12",
    gradeId: "grade12",
    phase: "FET Phase",
    phaseId: "FET",
    date: getRandomDate(),
  },
  {
    id: "28",
    title: "Probability Advanced",
    category: "Probability",
    categoryId: "probability15",
    description: "Advanced probability concepts and applications.",
    grade: "Grade 12",
    gradeId: "grade12",
    phase: "FET Phase",
    phaseId: "FET",
    date: getRandomDate(),
  },
  {
    id: "29",
    title: "Complex Numbers Advanced",
    category: "Complex Numbers",
    categoryId: "complexnumbers16",
    description: "Advanced understanding and working with complex numbers.",
    grade: "Grade 12",
    gradeId: "grade12",
    phase: "FET Phase",
    phaseId: "FET",
    date: getRandomDate(),
  },
  {
    id: "30",
    title: "Algebra Intermediate",
    category: "Algebra",
    categoryId: "algebra1",
    description: "Intermediate algebraic concepts and operations.",
    grade: "Grade 8",
    gradeId: "grade8",
    phase: "Senior Phase",
    phaseId: "Senior",
    date: getRandomDate(),
  },
  {
    id: "31",
    title: "Geometry Intermediate",
    category: "Geometry",
    categoryId: "geometry2",
    description:
      "Intermediate principles of geometry including shapes, angles, and theorems.",
    grade: "Grade 9",
    gradeId: "grade9",
    phase: "Senior Phase",
    phaseId: "Senior",
    date: getRandomDate(),
  },
  {
    id: "32",
    title: "Trigonometry Intermediate",
    category: "Trigonometry",
    categoryId: "trigonometry3",
    description: "Intermediate trigonometric concepts and problem-solving.",
    grade: "Grade 10",
    gradeId: "grade10",
    phase: "FET Phase",
    phaseId: "FET",
    date: getRandomDate(),
  },
  {
    id: "33",
    title: "Calculus Intermediate",
    category: "Calculus",
    categoryId: "calculus4",
    description:
      "Intermediate calculus topics including limits, derivatives, and integrals.",
    grade: "Grade 12",
    gradeId: "grade12",
    phase: "FET Phase",
    phaseId: "FET",
    date: getRandomDate(),
  },
  {
    id: "34",
    title: "Statistics Intermediate",
    category: "Statistics",
    categoryId: "statistics5",
    description: "Intermediate statistical methods and applications.",
    grade: "Grade 11",
    gradeId: "grade11",
    phase: "FET Phase",
    phaseId: "FET",
    date: getRandomDate(),
  },
  {
    id: "35",
    title: "Number Theory Intermediate",
    category: "Number Theory",
    categoryId: "numbertheory6",
    description: "Intermediate number theory concepts and applications.",
    grade: "Grade 12",
    gradeId: "grade12",
    phase: "FET Phase",
    phaseId: "FET",
    date: getRandomDate(),
  },
  {
    id: "36",
    title: "Finance Intermediate",
    category: "Finance",
    categoryId: "finance7",
    description:
      "Intermediate financial mathematics including investment analysis.",
    grade: "Grade 11",
    gradeId: "grade11",
    phase: "FET Phase",
    phaseId: "FET",
    date: getRandomDate(),
  },
  {
    id: "40",
    title: "Linear Equations Intermediate",
    category: "Linear Equations",
    categoryId: "linearequations8",
    description: "Intermediate techniques for solving linear equations.",
    grade: "Grade 10",
    gradeId: "grade10",
    phaseId: "fet",
    date: getRandomDate(),
  },
  {
    id: "41",
    title: "Shapes and Theorems Intermediate",
    category: "Shapes and Theorems",
    categoryId: "shapesandtheorems9",
    description: "Intermediate exploration of shapes and their theorems.",
    grade: "Grade 11",
    gradeId: "grade11",
    phaseId: "fet",
    date: getRandomDate(),
  },
  {
    id: "42",
    title: "Trigonometric Ratios Intermediate",
    category: "Trigonometric Ratios",
    categoryId: "trigonometricratios10",
    description:
      "Intermediate understanding and application of trigonometric ratios.",
    grade: "Grade 12",
    gradeId: "grade12",
    phaseId: "fet",
    date: getRandomDate(),
  },
  {
    id: "43",
    title: "Differentiation Intermediate",
    category: "Differentiation",
    categoryId: "differentiation11",
    description: "Intermediate differentiation techniques and applications.",
    grade: "Grade 12",
    gradeId: "grade12",
    phaseId: "fet",
    date: getRandomDate(),
  },
  {
    id: "44",
    title: "Data Analysis Intermediate",
    category: "Data Analysis",
    categoryId: "dataanalysis12",
    description: "Intermediate data analysis methods and interpretation.",
    grade: "Grade 11",
    gradeId: "grade11",
    phaseId: "fet",
    date: getRandomDate(),
  },
  {
    id: "45",
    title: "Number Patterns Intermediate",
    category: "Number Patterns",
    categoryId: "numberpatterns13",
    description: "Intermediate exploration of number patterns and sequences.",
    grade: "Grade 12",
    gradeId: "grade12",
    phaseId: "fet",
    date: getRandomDate(),
  },
  {
    id: "46",
    title: "Interest Calculations Intermediate",
    category: "Interest Calculations",
    categoryId: "interestcalculations14",
    description:
      "Intermediate understanding and calculation of different types of interest.",
    grade: "Grade 11",
    gradeId: "grade11",
    phaseId: "fet",
    date: getRandomDate(),
  },
  {
    id: "47",
    title: "Probability Intermediate",
    category: "Probability",
    categoryId: "probability15",
    description: "Intermediate probability concepts and applications.",
    grade: "Grade 12",
    gradeId: "grade12",
    phaseId: "fet",
    date: getRandomDate(),
  },
  {
    id: "48",
    title: "Complex Numbers Intermediate",
    category: "Complex Numbers",
    categoryId: "complexnumbers16",
    description: "Intermediate understanding and working with complex numbers.",
    grade: "Grade 12",
    gradeId: "grade12",
    phaseId: "fet",
    date: getRandomDate(),
  },
  {
    id: "49",
    title: "Algebra Basics",
    category: "Algebra",
    categoryId: "algebra1",
    description: "Introduction to algebraic concepts and operations.",
    grade: "Grade 8",
    gradeId: "grade8",
    phaseId: "senior",
    date: getRandomDate(),
  },
  {
    id: "50",
    title: "Geometry Fundamentals",
    category: "Geometry",
    categoryId: "geometry2",
    description:
      "Basic principles of geometry including shapes, angles, and theorems.",
    grade: "Grade 9",
    gradeId: "grade9",
    phaseId: "senior",
    date: getRandomDate(),
  },
  {
    id: "51",
    title: "Trigonometry Basics",
    category: "Trigonometry",
    categoryId: "trigonometry3",
    description: "Introduction to trigonometric concepts and applications.",
    grade: "Grade 9",
    gradeId: "grade9",
    phaseId: "senior",
    date: getRandomDate(),
  },
  {
    id: "52",
    title: "Calculus Basics",
    category: "Calculus",
    categoryId: "calculus4",
    description: "Introduction to calculus concepts and applications.",
    grade: "Grade 10",
    gradeId: "grade10",
    phaseId: "fet",
    date: getRandomDate(),
  },
  {
    id: "53",
    title: "Statistics Basics",
    category: "Statistics",
    categoryId: "statistics5",
    description: "Introduction to statistical concepts and applications.",
    grade: "Grade 11",
    gradeId: "grade11",
    phaseId: "fet",
    date: getRandomDate(),
  },
  {
    id: "54",
    title: "Number Theory Basics",
    category: "Number Theory",
    categoryId: "numbertheory6",
    description: "Introduction to number theory concepts and applications.",
    grade: "Grade 12",
    gradeId: "grade12",
    phaseId: "fet",
    date: getRandomDate(),
  },
  {
    id: "55",
    title: "Finance Basics",
    category: "Finance",
    categoryId: "finance7",
    description: "Introduction to financial mathematics concepts.",
    grade: "Grade 10",
    gradeId: "grade10",
    phaseId: "fet",
    date: getRandomDate(),
  },
  {
    id: "56",
    title: "Linear Equations Basics",
    category: "Linear Equations",
    categoryId: "linearequations8",
    description: "Introduction to linear equations and their applications.",
    grade: "Grade 8",
    gradeId: "grade8",
    phaseId: "senior",
    date: getRandomDate(),
  },
  {
    id: "57",
    title: "Shapes and Theorems Basics",
    category: "Shapes and Theorems",
    categoryId: "shapesandtheorems9",
    description: "Introduction to shapes and their theorems.",
    grade: "Grade 9",
    gradeId: "grade9",
    phaseId: "senior",
    date: getRandomDate(),
  },
  {
    id: "58",
    title: "Trigonometric Ratios Basics",
    category: "Trigonometric Ratios",
    categoryId: "trigonometricratios10",
    description: "Introduction to trigonometric ratios and their applications.",
    grade: "Grade 10",
    gradeId: "grade10",
    phaseId: "fet",
    date: getRandomDate(),
  },
  {
    id: "59",
    title: "Differentiation Basics",
    category: "Differentiation",
    categoryId: "differentiation11",
    description: "Introduction to differentiation and its applications.",
    grade: "Grade 12",
    gradeId: "grade12",
    phaseId: "fet",
    date: getRandomDate(),
  },
  {
    id: "60",
    title: "Data Analysis Basics",
    category: "Data Analysis",
    categoryId: "dataanalysis12",
    description: "Introduction to data analysis and interpretation.",
    grade: "Grade 11",
    gradeId: "grade11",
    phaseId: "fet",
    date: getRandomDate(),
  },
  {
    id: "61",
    title: "Number Patterns Basics",
    category: "Number Patterns",
    categoryId: "numberpatterns13",
    description: "Introduction to number patterns and sequences.",
    grade: "Grade 7",
    gradeId: "grade7",
    phaseId: "senior",
    date: getRandomDate(),
  },
  {
    id: "62",
    title: "Interest Calculations Basics",
    category: "Interest Calculations",
    categoryId: "interestcalculations14",
    description:
      "Introduction to interest calculations and their applications.",
    grade: "Grade 10",
    gradeId: "grade10",
    phaseId: "fet",
    date: getRandomDate(),
  },
  {
    id: "63",
    title: "Probability Basics",
    category: "Probability",
    categoryId: "probability15",
    description: "Introduction to probability concepts and applications.",
    grade: "Grade 11",
    gradeId: "grade11",
    phaseId: "fet",
    date: getRandomDate(),
  },
  {
    id: "64",
    title: "Complex Numbers Basics",
    category: "Complex Numbers",
    categoryId: "complexnumbers16",
    description: "Introduction to complex numbers and their applications.",
    grade: "Grade 12",
    gradeId: "grade12",
    phaseId: "fet",
    date: getRandomDate(),
  },
  {
    id: "65",
    title: "Algebra Intermediate",
    category: "Algebra",
    categoryId: "algebra1",
    description: "Intermediate algebraic concepts and operations.",
    grade: "Grade 8",
    gradeId: "grade8",
    phaseId: "senior",
    date: getRandomDate(),
  },
  {
    id: "66",
    title: "Geometry Intermediate",
    category: "Geometry",
    categoryId: "geometry2",
    description:
      "Intermediate principles of geometry including shapes, angles, and theorems.",
    grade: "Grade 9",
    gradeId: "grade9",
    phaseId: "senior",
    date: getRandomDate(),
  },
  {
    id: "67",
    title: "Trigonometry Intermediate",
    category: "Trigonometry",
    categoryId: "trigonometry3",
    description: "Intermediate trigonometric concepts and problem-solving.",
    grade: "Grade 10",
    gradeId: "grade10",
    phaseId: "fet",
    date: getRandomDate(),
  },
  {
    id: "68",
    title: "Calculus Intermediate",
    category: "Calculus",
    categoryId: "calculus4",
    description:
      "Intermediate calculus topics including limits, derivatives, and integrals.",
    grade: "Grade 12",
    gradeId: "grade12",
    phaseId: "fet",
    date: getRandomDate(),
  },
  {
    id: "69",
    title: "Statistics Intermediate",
    category: "Statistics",
    categoryId: "statistics5",
    description: "Intermediate statistical methods and applications.",
    grade: "Grade 11",
    gradeId: "grade11",
    phaseId: "fet",
    date: getRandomDate(),
  },
  {
    id: "70",
    title: "Number Theory Intermediate",
    category: "Number Theory",
    categoryId: "numbertheory6",
    description: "Intermediate number theory concepts and applications.",
    grade: "Grade 12",
    gradeId: "grade12",
    phaseId: "fet",
    date: getRandomDate(),
  },
];

// Category Cards

export { resourceCards, categoryCards, phaseCards, gradeCards };
